class TestCampaignPage():
    def test_campaign_group_ad_created(self, campaign_page):
        campaign_page.click_create_button()
        campaign_page.click_recognition_tabs()
        campaign_page.click_target_tabs()
        campaign_page.click_site_cell()
        campaign_page.fill_site_name_with_valid_url()
        campaign_page.click_target_tabs()
        campaign_page.rename_entity(campaign_page.CAMPAIGN_NAME)
        campaign_page.fill_campaign_form()
        campaign_page.click_continue_button()
        campaign_page.rename_entity(campaign_page.GROUP_NAME)
        campaign_page.click_russia_button()
        campaign_page.click_demography_section()
        campaign_page.fill_demography()
        campaign_page.click_demography_section()
        campaign_page.click_interest_section()
        campaign_page.click_interest_subsection()
        campaign_page.fill_interests()
        campaign_page.click_stop_interest_opener()
        campaign_page.has_stop_interest_content()
        campaign_page.fill_stop_interest()
        campaign_page.click_interest_section()
        campaign_page.click_device_section()
        campaign_page.click_mobile_checkbox()
        campaign_page.click_continue_button()
        campaign_page.rename_entity(campaign_page.AD_NAME)
        campaign_page.click_logo_input()
        campaign_page.click_image_item()
        campaign_page.fill_ad_inputs_and_textarea()
        campaign_page.click_media()
        campaign_page.has_mediatec_sidebar_image_content()
        campaign_page.click_image_item()
        campaign_page.submit_button_became_visible()
        campaign_page.click_submit_button()
        campaign_page.click_publish_button()
        campaign_page.click_send_bug_modal()

        campaign_page.hover_campaign_title()
        campaign_page.click_edit()
        assert self.campaign_page.check_title_input_value_campaign()
        assert self.campaign_page.check_site_name_value_campaign()
        assert self.campaign_page.check_action_select_value_campaign()
        assert self.campaign_page.check_strategy_select_value_campaign()
        assert self.campaign_page.check_budget_input_value_campaign()
        assert self.campaign_page.check_budget_period_input_value_campaign()
        campaign_page.click_cancel_button()
        campaign_page.click_confirm_cancel_button()
        campaign_page.click_group_tabs()
        assert self.campaign_page.check_group_title()
        campaign_page.hover_group_title()
        campaign_page.click_edit()
        assert self.campaign_page.check_title_input_value_group()
        assert self.campaign_page.check_selected_region()
        assert self.campaign_page.check_ages()
        assert self.campaign_page.check_pegi()
        assert self.campaign_page.check_interest()
        assert self.campaign_page.check_stop_interest()
        assert self.campaign_page.check_devices()
        campaign_page.click_cancel_button()
        campaign_page.click_confirm_cancel_button()
        campaign_page.click_ad_tab()
        assert self.campaign_page.check_ad_title()
        campaign_page.hover_ad_title()
        campaign_page.click_edit()
        assert self.campaign_page.check_ad_name()
        assert self.campaign_page.check_ad_short_description()
        assert self.campaign_page.check_ad_long_description()
        assert self.campaign_page.check_ad_button_text()
        assert self.campaign_page.check_ad_advertiser()
        campaign_page.click_cancel_button()
        campaign_page.click_confirm_cancel_button()
        campaign_page.delete_entity()