class TestCampaignPage():
    def test_campaign_group_ad_created(self, campaign_page):
        campaign_page.click_create_button()
        campaign_page.click_recognition_tabs()
        campaign_page.click_target_tabs()
        campaign_page.click_site_cell()
        campaign_page.fill_site_name_with_valid_url()
        campaign_page.click_target_tabs()
        campaign_page.rename_entity(campaign_page.CAMPAIGN_NAME)
        campaign_page.fill_campaign_form()
        campaign_page.click_continue_button()
        campaign_page.rename_entity(campaign_page.GROUP_NAME)
        campaign_page.click_russia_button()
        campaign_page.click_interest_section()
        campaign_page.click_interest_subsection()
        campaign_page.fill_interests()
        campaign_page.click_stop_interest_opener()
        assert campaign_page.has_stop_interest_content(), "Блок исключения интересов не отображается"
        campaign_page.fill_stop_interest()
        campaign_page.click_interest_section()
        campaign_page.click_device_section()
        campaign_page.click_mobile_checkbox()
        campaign_page.click_continue_button()
        assert campaign_page.has_ads_inputs_content(), "Поля для ввода объявления не отображаются"
        campaign_page.rename_entity(campaign_page.AD_NAME)
        campaign_page.click_logo_input()
        campaign_page.click_image_item()
        campaign_page.fill_ad_inputs_and_textarea()
        campaign_page.click_media()
        campaign_page.click_image_item()
        assert campaign_page.submit_button_became_visible(), "Кнопка отправки не появилась"
        campaign_page.click_submit_button()
        campaign_page.click_publish_button()